"""
Tile.py
Defines a Tile in the Maze
Adapted from UCSD CSE12

Do NOT edit this file.
"""

# A single unit in a maze
class Tile:
    # Constructor
    def __init__(self, row, col, wall):
        self.__row = row            # row of the Tile (int)
        self.__col = col            # col of the Tile (int)
        self.__isWall = wall  # Whether the Tile is a wall (bool)
        self.visited = False  # Whether we have visited this Tile (bool)
        self.previous = None  # The Tile we visited prior to this one (Tile)
    
    # Return the row
    def getRow(self):
        return self.__row 
    
    # Return the col
    def getCol(self):
        return self.__col
    
    # Return whether the Tile is a wall
    def getIsWall(self):
        return self.__isWall 
    
    # Return whether we have visited this Tile
    def isVisited(self):
        return self.visited
    
    # Return the previous Tile
    def getPrevious(self):
        return self.previous
    
    # Mark this Tile as visited
    def visit(self):
        self.visited = True 

    # Set the previous Tile
    def setPrevious(self, previous):
        self.previous = previous

    # Print out the values of this Tile
    def printAttributes(self):
        print("row: {}, col: {}, isWall: {}, visited: {}, previous: {}".format(
                    self.__row, self.__col, self.__isWall, 
                    self.visited, self.previous))